### ISSUE TITLE
Add Optional Application Domain Setting for GitLab

### ISSUE THREAD

**Issue by Ralkage** [FriendsOfFlarum/oauth#2]
In order for me to sunset my auth-gitlab extension, I recently implemented the ability to add an optional Application Domain for those that self-host their own GitLab instances. I am setting this as a reminder so I don't forget to submit a PR with this additional option or if someone beats me to it 😆 

If a validation rule can be made for this option to only allow `https` in the URL as well, then that would be the icing on the cake.

**Validation Rule:** `'url'   => ['regex' => '/^((?:https?\:\/\/|www\.)(?:[-a-z0-9]+\.)*[-a-z0-9]+.*)$/'],`

The field can also look like this in the settings menu for GitLab right underneath the Client Secret:

![image](https://user-images.githubusercontent.com/2059356/93558101-b3f07d80-f94a-11ea-8c57-6b9c504f0fad.png)

**Comment by luceos** [comment]
@Ralkage feel free to submit a PR 👍 I do think it makes sense, but the problem here is that the label on the frontend also has to change. Would the "authorize with GitLab" label remain the same, people would be confused seeing the URL change to the custom on-premise install.. The label could contain the domain perhaps (gitlab.com or myinstance.com).

**Comment by datitisev** [comment]
I don't think we need validation. I added the field, but it doesn't have a description & it doesn't change the button label (not entirely sure that it should).
